Docs: add SECURITY.md file for reporting vulnerabilities Related to #42
gelecekbilimde/gelecekbilimde-backend pull request #140
Opened 2024-09-19 10:50 UTC by aleyna-yildizli

2024-09-19 11:18 UTC, alpemreelmas approved these changes

2024-09-19 12:03 UTC, agitrubard requested changes

2024-09-19 12:03 UTC, agitrubard commented on SECURITY.md
> +   **Security Team Contact**: [mert.cikla@gelecekbilimde.net](mailto:mert.cikla@gelecekbilimde.net)
Buraya kişi mailinden ziyade, ekipteki belli insanların erişimi olan aşağıdaki örnekteki gibi ortak mail ekleyebilir miyiz?
```suggestion
   **Security Team Contact**: [software@gelecekbilimde.net](mailto:software@gelecekbilimde.net)
```

2024-09-19 12:03 UTC, agitrubard commented on SECURITY.md
> +| 0.x     | :x:                |
Versiyon olmadığı için kaldırmak faydalı olabilir
```suggestion
```

2024-09-19 12:03 UTC, agitrubard commented on SECURITY.md
> +---
```suggestion
```

2024-09-19 12:04 UTC, agitrubard commented
@aleyna-yildizli diğer arkadaşları da reviewer olarak ekleyebilir miyiz? Ek olarak pull request başlığını da standartlarımıza uygun olacak şekilde düzenleyebilirsek süper olur

2024-09-20 18:36 UTC, mert-ayhan approved these changes

2024-09-22 12:56 UTC, ferhatozcelik approved these changes

2024-09-23 10:31 UTC, agitrubard approved these changes

2024-09-23 10:58 UTC, merged